version: '3.8'

services:
  backend:
    build:
      context: ./backend-django/backend
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000 
    volumes:

       - ./backend-django/backend:/app

    ports:
      - "8000:8000"
    env_file: .env 
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mynetwork

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: mydatabases2
      MYSQL_USER: user1
      MYSQL_PASSWORD: White450602
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-prootpassword"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mynetwork

 


networks:
  mynetwork:

volumes:
  db_data: