version: '3.8'

services:
  backend:
    build:
      context: ./backend-django/backend
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000 
    volumes:

       - ./backend-django/backend:/app

    ports:
      - "8000:8000"
    env_file: .env 
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: mydatabases
      MYSQL_USER: user1
      MYSQL_PASSWORD: White450602
      MYSQL_ROOT_PASSWORD: rootpassword

    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mynetwork

 


networks:
  mynetwork:

volumes:
  db_data:
