from django.contrib import admin
from django.urls import path
from .views import *
from .oauthcallback import google_auth_callback
from rest_framework_simplejwt.views import TokenRefreshView


urlpatterns = [
    path("Register/",Register().as_view(),name="register-page"),
    path("verifyemail/<str:user_id>/",verification().as_view(),name="verify email"),
    path('check_verify/', VerifyEmailStatus().as_view(),name="Check-verify"),
    path('Login/',Login().as_view(),name='login-page'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('fechlocations/',FetchLocations.as_view(),name='locations'),
    path('fechworkout/',Fetchworkoutype.as_view(),name='fechworkout'),
    path('fechexercisepalcetype/',fectexerciseplacetype.as_view(),name='fechexerciseplacetype'),
    path('filter/',filterlocation.as_view(),name='filter'),
    path('creatparty/',CreatePartyView.as_view(),name='creatparty'),
    path('fecthcreateparty/',fecthcreatepaty.as_view(),name='fecthcreateparty'),
    path('fecthjoinparty/',fecthjoinparty.as_view(),name='fecthjoinparty'),
    path('fecthmember/',fecthmember.as_view(),name='fecthmember'),
    path('editparty/',updatateparty.as_view(),name='updateparty'),
    path('addmember/',addmember.as_view(),name='addmember'),
    path('removemember/',Removemember.as_view(),name='removemember'),
    path('deleteparty/',Deleteparty.as_view(),name='deleteparty'),
    path('fecthallparty/',fecthallparty.as_view(),name='fecthallparty'),
    path('filterparty/',filterParty.as_view(),name='filterparty'),
    path('joinparty/',joinrequest.as_view(),name='joinparty'),
    path('saveFCMtoken/',SaveFCMTokenAPIView.as_view(),name='saveFVMtoken'),
    path('joinrequest/',responseRequest.as_view(),name='joinrequest'),
    path('fecthfriends/',fecthallfriend.as_view(),name='fecthallfriend'),
    path('serachfriend/',SearchFriendView.as_view(),name='searchfriend'),
    path('feactProfile/',FetchUserProfile.as_view(),name='fecthproflie'),
    path('friendrequest/',Friendrequest.as_view(),name='friendrequest'),
    path('feachallfriend/',showfriendrequest.as_view(),name='feachallfriend'),
    path('aceptfriend/',acepceptfriend.as_view(),name='aceptfriend'),
    path('rejectfirend/',rejectfriend.as_view(),name='rejectfriend'),
    path('fecthallrequest/',fectallrequest.as_view(),name='fecthallrequest'),
    path('rejectedjoinrequest/',rejectedjointrequest.as_view(),name='rejectedjoinrequest'),
    path('sendinvitation/',SendInvitationView.as_view(),name='sendinvitation'),
    path('fecthallinvitation/',ReceivedInvitationsView.as_view(),name='fecthallinvitation'),
    path('acceptedinvitation/',RespondInvitationView.as_view(),name='acceptedinvitation'),
    path('leaveparty/',leaveparty.as_view(),name='leaveparty'),
    path('updateparty/<int:party_id>/', updatateparty.as_view(), name='update-party'),
    path('refresh_token/',RefreshAccessTokenView.as_view(),name='refresh_token/'),
    path('rejectedInvite/',rejectedinvitetaion.as_view(),name='rejectedInvite'),
    path("oauth2callback/", google_auth_callback, name="oauth2callback"),
    path('remcomendparty/',RecommendedPartyView.as_view(),name='remcomendparty'),
    path('updateprofile/',UpdateProfile.as_view(),name='updateprofile'),
    path('addtocalendar/',addTocalendar.as_view(),name='addtocalendar'),
    path('getmemberevent/<int:party_id>/',getmemberevent.as_view(),name='getmemberevent'),
    path('updatememberevent/<int:party_id>/',updatememberevent.as_view(),name='updatememberevent'),
    path('upcomingparty/',upcomingparty.as_view(),name='upcomingparty'),
    path('recomendparty/',recomenparty.as_view(),name='recomendparty'),
    path('check_status/',check_status.as_view(),name='check_status'),
    path('notitomeber/',NotiToMember.as_view(),name='notitomeber'),
    path('fecthchrckinmember/',fecthcheckinmember.as_view(),name='fecthchrckinmember'),
    path('checkinparty/',CheckInToWorkout.as_view(),name='checkinparty'),
    path('checkoutparty/',Checkoutoworkout.as_view(),name='checkoutparty'),
    path('checkinstatus/',getcheckinstatus.as_view(),name='checkinstatus'),
    path('cencelcheckin/',Checkoutoworkout.as_view(),name='cencelcheckin'),
    path('startworkout/',StartWorkout.as_view(),name='startworkout'),
    path('getpartystatus/',GetpartyStatus.as_view(),name='getpartystatus'),
    path('fecthworkouttime/',FetchWorkoutTime.as_view(),name='fecthworkouttime'),
    path('finishparty/',finishparty.as_view(),name='finishparty'),
    path('getfinishworkout/',getfinishworkout.as_view(),name='getfinishworkout'),
    path('finishworkout/',finishworkout.as_view(),name='finishworkout'),
    path('fecthworkoutstatus/',fectworkoutstatus.as_view(),name='fecthworkoutstatus'),
    path('submitvote/',SubmitReview.as_view(),name='submitvote'),
    path("upload_memory/", UploadPartyMemory.as_view(), name="upload_memory"),
    path('fecthhistorygallary/',UserPartyHistory.as_view(),name='fecthhistorygallary'),
    path('creatpartyhistory/',CreatupartyHistory.as_view(),name='creatpartyhistory'),
    path('sharememory/',ShareMemoryView.as_view(),name='sharememory'),
    path('partyposts/',PartyPostView.as_view(),name='partyposts'),
    path('Like/<int:post_id>/',ToggleLikePost.as_view(),name='Like'),
    path('add_comment/',PartyCommentView.as_view(),name='add_comment'),
    path('sharememoryforleader/',ShareMemoryForLeaderView.as_view(),name='sharememoryforleader'),
    path('deletepost/', DeletePostView.as_view(), name='deletepost'),
    path('fecthTopparty/',FetchUserTopParty.as_view(),name='fecthTopparty'),
    path('searchparty/', SearchPartyView.as_view(), name='search_party'),
    path('gettallupdate/',gettallupdate.as_view(),name='gettallupdate'),
    path('joinrequestcount/',joinrequestcount.as_view(),name='joinrequestcount/'),
    path('invitationcoint/',invitationscont.as_view(),name='invitationcoint'),
    path('deletepartyalbum/',deletehistoryparty.as_view(),name='deletepartyalbum'),
    path("request-password-reset/",RequestPasswordResetView.as_view(), name="request-password-reset"),
    path("removefriend/<str:friend_id>/", RemoveFriendView.as_view(),name='removefriend'),
    ## ด้านล้างคือurl สำหรับ addmin
     path('admin-login/', AdminLoginView.as_view(), name='admin-login'),
     path('admin-refresh/', TokenRefreshView.as_view(), name='admin-refresh'),
     path('admingetalluser/',AdminGetAllUser.as_view(),name='admingetalluser/'),
     path('EditUser/<str:user_id>/',AdminEditUser.as_view(),name='EditUser/'),
     path('AdmindeleteUser/<str:user_id>/',AdminDeleteUser.as_view(),name='AdmindeleteUser/'),
     path('Adminupdatelocation/<int:location_id>/',AdminUpdateLocation.as_view(),name='Adminupdatelocation'),
     path('Admindeletelocation/<int:location_id>/',deletelocation.as_view(),name='Admindeletelocation'),
     path('Adminaddlocation/',AdminCreateLocation.as_view(),name='Adminaddlocation'),
     path('Adminaddlocationtype/',Addlocationtype.as_view(),name='Adminaddlocationtype'),
     path('AddExercisetype/',addExercisetype.as_view(),name='AddExercisetype/'),
     path('deleteExercisetype/<int:exercise_typeId>/',deleteExcercisetype.as_view(),name='deleteExercisetype/'),
     path('Admingetallmember/',adminfecthmember.as_view(),name='Admingetallmember'),
     path("system_updates/",SystemUpdateView.as_view(),name='system_updates'),
     path("getdashborddata/",DashboardDataView.as_view(),name='getdashborddata'),
     path("admindeletepost/<int:post_id>/",admindeletepost.as_view(),name='admindeletepost'),
     path("admindeleteupdate/<int:update_id>/", admindeleteupdate.as_view(), name='admindeleteupdate'),
     path("adminprofile/",AdminProfileView.as_view(),name='adminprofile'),
     path('admineditprofile/',UpdateAdminProfile.as_view(),name='admineditprofile'),
     path('admindeleteparty/<int:party_id>/', AdminDeleteParty.as_view(), name='admin_delete_party'),
     
     
     
     
     
     
]

    