# Generated by Django 5.1.4 on 2024-12-20 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Smartwityouapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exerciseplace",
            name="close_time",
        ),
        migrations.RemoveField(
            model_name="exerciseplace",
            name="open_time",
        ),
        migrations.RemoveField(
            model_name="exerciseplace",
            name="opening_day",
        ),
        migrations.CreateModel(
            name="OpeningHours",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "day_of_week",
                    models.CharField(
                        choices=[
                            ("SUN", "Sunday"),
                            ("MON", "Monday"),
                            ("TUE", "Tuesday"),
                            ("WED", "Wednesday"),
                            ("THU", "Thursday"),
                            ("FRI", "Friday"),
                            ("SAT", "Saturday"),
                        ],
                        max_length=10,
                    ),
                ),
                ("open_time", models.TimeField(blank=True, null=True)),
                ("close_time", models.TimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("Open", "Open"), ("Closed", "Closed")],
                        default="Open",
                        max_length=10,
                    ),
                ),
                (
                    "exercise_place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opening_hours",
                        to="Smartwityouapp.exerciseplace",
                    ),
                ),
            ],
        ),
    ]
