# Generated by Django 5.1.4 on 2024-12-21 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Smartwityouapp", "0002_remove_exerciseplace_close_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exerciseplace",
            name="place_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="exercise_places/"
            ),
        ),
    ]
