# Generated by Django 5.1.4 on 2024-12-21 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Smartwityouapp", "0003_exerciseplace_place_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exerciseplace",
            name="latitude",
            field=models.DecimalField(decimal_places=10, max_digits=15),
        ),
        migrations.AlterField(
            model_name="exerciseplace",
            name="longitude",
            field=models.DecimalField(decimal_places=10, max_digits=15),
        ),
    ]
