# Generated by Django 5.1.4 on 2024-12-21 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Smartwityouapp", "0004_alter_exerciseplace_latitude_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exerciseplacetype",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="exerciseplace",
            name="exercise_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Smartwityouapp.exerciseplacetype",
            ),
        ),
    ]
