# Generated by Django 5.1.4 on 2024-12-21 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Smartwityouapp", "0005_exerciseplacetype_alter_exerciseplace_exercise_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exerciseplace",
            name="latitude",
            field=models.DecimalField(decimal_places=15, max_digits=20),
        ),
        migrations.AlterField(
            model_name="exerciseplace",
            name="longitude",
            field=models.DecimalField(decimal_places=15, max_digits=20),
        ),
    ]
