# Generated by Django 5.1.4 on 2024-12-21 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Smartwityouapp", "0006_alter_exerciseplace_latitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openinghours",
            name="day_of_week",
            field=models.CharField(
                choices=[
                    ("อาทิตย์", "Sunday"),
                    ("จันทร์", "Monday"),
                    ("อังคาร", "Tuesday"),
                    ("พุทธ", "Wednesday"),
                    ("พฤหัส", "Thursday"),
                    ("ศุกร์", "Friday"),
                    ("เสาร์", "Saturday"),
                    ("ทุกวัน", "Everyday"),
                ],
                max_length=10,
            ),
        ),
    ]
