# Generated by Django 5.1.4 on 2024-12-21 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Smartwityouapp", "0007_alter_openinghours_day_of_week"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openinghours",
            name="day_of_week",
            field=models.CharField(
                choices=[
                    ("Sunday", "อาทิตย์"),
                    ("Monday", "จันทร์"),
                    ("Tuesday", "อังคาร"),
                    ("wednesday", "พุทธ"),
                    ("Thursday", "พฤหัส"),
                    ("Friday", "ศุกร์"),
                    ("Saturday", "เสาร์"),
                    ("Everyday", "ทุกวัน"),
                ],
                max_length=10,
            ),
        ),
    ]
