# Generated by Django 5.1.4 on 2025-01-20 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Smartwityouapp", "0010_userexercisetype"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userexercisetype",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="userexercisetype",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="userexercisetype",
            name="start_time",
        ),
    ]
