# Generated by Django 5.1.4 on 2025-01-26 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Smartwityouapp", "0011_remove_userexercisetype_duration_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="friend",
            unique_together={("user", "friend_user")},
        ),
    ]
