# Generated by Django 5.1.4 on 2025-01-27 12:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Smartwityouapp", "0012_alter_friend_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="friend",
            field=models.ManyToManyField(
                related_name="friend_set",
                through="Smartwityouapp.Friend",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
