# Generated by Django 5.1.4 on 2025-01-27 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Smartwityouapp", "0013_customuser_friend"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="friend",
        ),
    ]
