# Generated by Django 5.1.4 on 2025-02-04 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Smartwityouapp", "0014_remove_customuser_friend"),
    ]

    operations = [
        migrations.AddField(
            model_name="party",
            name="google_event_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
