# Generated by Django 5.1.4 on 2025-02-09 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Smartwityouapp", "0016_backgroundprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartyMemberEvent",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "google_event_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Smartwityouapp.partymember",
                    ),
                ),
            ],
        ),
    ]
