# Generated by Django 5.1.4 on 2025-02-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Smartwityouapp", "0018_partyphoto"),
    ]

    operations = [
        migrations.AddField(
            model_name="party",
            name="status",
            field=models.CharField(
                choices=[
                    ("ongoing", "กำลังดำเนินการ"),
                    ("completed", "จบแล้ว"),
                    ("archived", "เก็บถาวร"),
                ],
                default="ongoing",
                max_length=10,
            ),
        ),
    ]
