# Generated by Django 5.1.4 on 2025-02-14 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Smartwityouapp", "0019_party_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="partymember",
            name="has_liked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="partymember",
            name="has_reviewed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name="partymember",
            unique_together={("user", "party")},
        ),
    ]
