# Generated by Django 5.1.4 on 2025-02-14 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Smartwityouapp",
            "0020_partymember_has_liked_partymember_has_reviewed_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="party",
            name="like_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
