# Generated by Django 5.1.4 on 2025-02-14 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Smartwityouapp", "0022_partylike"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="party",
            name="like_count",
        ),
    ]
