# Generated by Django 5.1.4 on 2025-02-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Smartwityouapp", "0023_remove_party_like_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="party",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting", "รอการดำเนินการ"),
                    ("ongoing", "กำลังดำเนินการ"),
                    ("completed", "จบแล้ว"),
                    ("archived", "เก็บถาวร"),
                ],
                default="waiting",
                max_length=10,
            ),
        ),
    ]
