# Generated by Django 5.1.4 on 2025-02-19 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Smartwityouapp", "0024_alter_party_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="partymember",
            name="checkin_status",
            field=models.BooleanField(default=False),
        ),
    ]
