# Generated by Django 5.1.4 on 2025-02-19 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Smartwityouapp", "0025_partymember_checkin_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="partymember",
            name="checkin_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
