# Generated by Django 5.1.4 on 2025-02-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Smartwityouapp", "0026_partymember_checkin_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="partymember",
            name="finish_workout",
            field=models.BooleanField(default=False),
        ),
    ]
