# Generated by Django 5.1.4 on 2025-02-21 15:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Smartwityouapp", "0027_partymember_finish_workout"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartyHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("leader_name", models.CharField(max_length=255)),
                ("date", models.DateField()),
                (
                    "completed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("party_rating", models.FloatField(blank=True, null=True)),
                ("leader_rating", models.FloatField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LeaderVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "leader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "voter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leader_votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "party_history",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Smartwityouapp.partyhistory",
                    ),
                ),
            ],
            options={
                "unique_together": {("party_history", "voter")},
            },
        ),
        migrations.DeleteModel(
            name="PartyLike",
        ),
    ]
