# Generated by Django 5.1.4 on 2025-02-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Smartwityouapp", "0028_partyhistory_leadervote_delete_partylike"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partyhistory",
            name="leader_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
