# Generated by Django 5.1.4 on 2025-02-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Smartwityouapp", "0029_alter_partyhistory_leader_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="partyhistory",
            name="party_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
