# Generated by Django 5.1.4 on 2025-02-21 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Smartwityouapp", "0030_partyhistory_party_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="partyhistory",
            name="party",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Smartwityouapp.party",
            ),
        ),
    ]
