# Generated by Django 5.1.4 on 2025-02-22 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Smartwityouapp", "0031_partyhistory_party"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="leader_score",
            field=models.FloatField(default=0.0),
        ),
    ]
