# Generated by Django 5.1.4 on 2025-02-22 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Smartwityouapp", "0032_customuser_leader_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="leadervote",
            name="review_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
