# Generated by Django 5.1.4 on 2025-02-22 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Smartwityouapp", "0033_leadervote_review_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="partyhistory",
            name="party",
        ),
    ]
