# Generated by Django 5.1.4 on 2025-02-22 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Smartwityouapp", "0034_remove_partyhistory_party"),
    ]

    operations = [
        migrations.AddField(
            model_name="partyhistory",
            name="leader",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="led_parties",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
