# Generated by Django 5.1.4 on 2025-02-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Smartwityouapp", "0035_partyhistory_leader"),
    ]

    operations = [
        migrations.AddField(
            model_name="partyhistory",
            name="party_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
