# Generated by Django 5.1.4 on 2025-02-26 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Smartwityouapp", "0040_partycomment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="partypost",
            name="likes",
        ),
    ]
