# Generated by Django 5.1.4 on 2025-04-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Smartwityouapp", "0043_systemupdate"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercisetype",
            name="nummerber",
            field=models.IntegerField(default=0),
        ),
    ]
